

/* Create Tables */

CREATE TABLE SCHOOL_COURSE
(
	COURSE_NO number(4,0) NOT NULL,
	SUBJECT_NO number(4,0) NOT NULL,
	PROF_NO number(4,0) NOT NULL,
	COURSE_NAME varchar2(200) NOT NULL,
	COURSE_QUOTA number(3,0) DEFAULT 30,
	COURSE_REG_CNT number(3,0) DEFAULT 0,
	COURSE_CANCEL_CNT number(3,0) DEFAULT 0,
	COURSE_CLOSED char(1) DEFAULT '''N''',
	COURSE_CREATE_DATE date,
	PRIMARY KEY (COURSE_NO)
);


CREATE TABLE SCHOOL_COURSE_REGRISTRATIONS
(
	REG_NO number(5,0) NOT NULL,
	COURSE_NO number(4,0) NOT NULL,
	STUD_NO number(4,0) NOT NULL,
	REG_CANCELED char(1) DEFAULT '''N''',
	REG_COMPLETED char(1) DEFAULT '''N''',
	REG_SCORE number(2,1),
	REG_CREATE_DATE date,
	PRIMARY KEY (REG_NO),
	CONSTRAINT COURSE_REG_UK UNIQUE (COURSE_NO, STUD_NO)
);


CREATE TABLE SCHOOL_DEPT
(
	DEPT_NO number(4,0) NOT NULL,
	DEPT_NAME varchar2(100) NOT NULL,
	PRIMARY KEY (DEPT_NO)
);


CREATE TABLE SCHOOL_PROFESSORS
(
	PROF_NO number(4,0) NOT NULL,
	DEPT_NO number(4,0) NOT NULL,
	PROF_NAME varchar2(100) NOT NULL,
	PROF_POSITION varchar2(50),
	PROF_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (PROF_NO)
);


CREATE TABLE SCHOOL_STUDENTS
(
	STUD_NO number(4,0) NOT NULL,
	STUD_NAME varchar2(100) NOT NULL,
	STUD_GRADE number(1) NOT NULL,
	STUD_CREATE_DATE date DEFAULT SYSDATE,
	DEPT_NO number(4,0) NOT NULL,
	PRIMARY KEY (STUD_NO)
);


CREATE TABLE SCHOOL_SUBJECTS
(
	SUBJECT_NO number(4,0) NOT NULL,
	SUBJECT_NAME varchar2(200) NOT NULL,
	SUBJECT_CREATE_DATE date DEFAULT SYSDATE,
	DEPT_NO number(4,0) NOT NULL,
	PRIMARY KEY (SUBJECT_NO)
);



/* Create Foreign Keys */

ALTER TABLE SCHOOL_COURSE_REGRISTRATIONS
	ADD FOREIGN KEY (COURSE_NO)
	REFERENCES SCHOOL_COURSE (COURSE_NO)
;


ALTER TABLE SCHOOL_PROFESSORS
	ADD FOREIGN KEY (DEPT_NO)
	REFERENCES SCHOOL_DEPT (DEPT_NO)
;


ALTER TABLE SCHOOL_STUDENTS
	ADD FOREIGN KEY (DEPT_NO)
	REFERENCES SCHOOL_DEPT (DEPT_NO)
;


ALTER TABLE SCHOOL_SUBJECTS
	ADD FOREIGN KEY (DEPT_NO)
	REFERENCES SCHOOL_DEPT (DEPT_NO)
;


ALTER TABLE SCHOOL_COURSE
	ADD FOREIGN KEY (PROF_NO)
	REFERENCES SCHOOL_PROFESSORS (PROF_NO)
;


ALTER TABLE SCHOOL_COURSE_REGRISTRATIONS
	ADD FOREIGN KEY (STUD_NO)
	REFERENCES SCHOOL_STUDENTS (STUD_NO)
;


ALTER TABLE SCHOOL_COURSE
	ADD FOREIGN KEY (SUBJECT_NO)
	REFERENCES SCHOOL_SUBJECTS (SUBJECT_NO)
;



/* Comments */

COMMENT ON COLUMN SCHOOL_COURSE.PROF_NO IS '교수의 고유한 번호';
COMMENT ON COLUMN SCHOOL_COURSE.COURSE_QUOTA IS '과정별 최대 수강인원
기본값 30
최대 인원수 100';
COMMENT ON COLUMN SCHOOL_COURSE.COURSE_REG_CNT IS '해당 과정을 신청학 학생수
수강신청정보가 추가될 때마다 1씩 증가';
COMMENT ON COLUMN SCHOOL_COURSE.COURSE_CANCEL_CNT IS '해당 과정을 수강하다가 취소한 학생 수
수강신청테이블의 REG_CANCELED_가 Y로 변경되면 1씩 증가';
COMMENT ON COLUMN SCHOOL_COURSE_REGRISTRATIONS.STUD_NO IS '학생의 고유한 번호';
COMMENT ON COLUMN SCHOOL_COURSE_REGRISTRATIONS.REG_CANCELED IS '수강신청 취소여부는 Y, N으로 지정,
기본값은 N';
COMMENT ON COLUMN SCHOOL_COURSE_REGRISTRATIONS.REG_COMPLETED IS '수강신청 수료여부는 Y, N으로 지정,
기본값은 N';
COMMENT ON COLUMN SCHOOL_COURSE_REGRISTRATIONS.REG_SCORE IS '평가점수는 0.0 ~ 4.5,
기본값은 null';
COMMENT ON COLUMN SCHOOL_DEPT.DEPT_NO IS '학과의 고유한 번호';
COMMENT ON COLUMN SCHOOL_DEPT.DEPT_NAME IS '학과의 이름';
COMMENT ON COLUMN SCHOOL_PROFESSORS.PROF_NO IS '교수의 고유한 번호';
COMMENT ON COLUMN SCHOOL_PROFESSORS.DEPT_NO IS '학과 테이블의 학과번호를 참조';
COMMENT ON COLUMN SCHOOL_PROFESSORS.PROF_POSITION IS '주교수, 부교수, 정교수, 겸임교수, 석좌교수 등의 값이 가능';
COMMENT ON COLUMN SCHOOL_STUDENTS.STUD_NO IS '학생의 고유한 번호';
COMMENT ON COLUMN SCHOOL_STUDENTS.DEPT_NO IS '학과의 고유한 번호';
COMMENT ON COLUMN SCHOOL_SUBJECTS.DEPT_NO IS '학과의 고유한 번호';



